services:
  manage-server:
    image: nginx:latest
    container_name: manage-server
    ports:
      - "90:90"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-net
networks:
  backend-net:
    external: true