services:
  manage-server:
    image: nginx:latest
    container_name: manage-server
    ports:
      - "90:90"
    volumes:
      - ./manage-server/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-net

  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api-gateway
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend-net

networks:
  backend-net:
    external: true
